### ISSUE TITLE
Test Authentication Sources series of errors within "SessionHandlerPHP.php"

### ISSUE THREAD

**Issue by MarchosiasM** [simplesamlphp/simplesamlphp#1006]
Within the simpleSAML installer screen from HTTPS, when I attempt to access "test authentication sources" I receive a handful of warnings.

1. Configure simpleSAML for HTTPS
2. Go to authentication
3.  Click on test configured authentication sources
4. See normal screen with handful of warnings at bottom

It's hard to say if I've never seen these warnings before. They're dark grey on a black background but I just noticed them.

Anyway, I'd expect for the warnings to not be there.

**Screenshots or logs**

![image](https://user-images.githubusercontent.com/34724649/49249932-63550c80-f3d2-11e8-9502-40c56f102699.png)

Here's what the warnings say:
```
Warning: session_name(): Cannot change session name when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 72

Warning: session_id(): Cannot change session id when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 191

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 115

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 117

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 243

Warning: session_id(): Cannot change session id when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 191

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 115

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in C:\xampp7\htdocs\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 117
```
As far as I can tell, this does not appear to impair the functionality of anything. The SAML Demo Example connects and seemingly outputs the AuthData accurately.

**Comment by jaimeperez** [comment]
Hi @MarchosiasM,

This sounds a lot like #793. Are you running PHP 7.x? If so, can you try installing SimpleSAMLphp from the current master, and tell us if the error persists?

**Comment by tvdijen** [comment]
Hi @MarchosiasM, could you get back at us and tell us if `master` fixes things for you?

**Comment by tvdijen** [comment]
Closing, no response.. Issues should be fixed in the latest release

**Comment by inblueswithu** [comment]
Hi,

I understand this issue is closed. But I'm getting an almost similar error with the following configuration (PHP 7.3.3):

![Screen Shot 2019-03-28 at 10 22 20 AM](https://user-images.githubusercontent.com/1096515/55165212-64f5cd80-5143-11e9-92b3-3290faba2e5d.png)

I'm not using Memchache or Predis. So above configuration seems correct.

I'm getting these errors at the bottom of the page when I visit the Test Authentication Sources page or Metadata page (`..../module.php/saml/sp/metadata.php/default-sp?output=xhtml`):
```
Warning: session_name(): Cannot change session name when headers already sent in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 72

Warning: session_id(): Cannot change session id when headers already sent in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 173

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 225

Warning: session_id(): Cannot change session id when headers already sent in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 173
```

I would appreciate any help in this. 

Thanks.

**Comment by tvdijen** [comment]
Thanks @inblueswithu, I'll see if I can reproduce and hopefully fix this

**Comment by tvdijen** [comment]
Hi @inblueswithu! I'm unable to reproduce this, so this must be a configuration issue on your end.

**Comment by inblueswithu** [comment]
Alright. This is interesting. I'm actually using `php:7.3-apache` docker image to build simplesamlphp container. I see all those warnings in the page but they are errors in the logs. However, when I  changed the docker base image to `php:7.2-apache`, I see no errors what so ever.

Also, I have been getting intermittent segmentation faults with 7.3 image. I'm not sure if that has been solved by using 7.2, yet. I'll come back and post if anything changes. If this works out, I'll also try to minimize my configuration to bare minimum to replicate the above issue with 7.3.

**Comment by jaimeperez** [comment]
Hi @chinmaya-n,

I believe the warnings you've been seeing were due to a change in the behaviour of PHP and have been fixed recently (see #1176). Also, the segmentation faults were reported in #1158. Could you please help us out in reproducing the segfaults with a stack trace so that we can report that properly to PHP and get it fixed upstream? Thanks!

**Comment by chinmaya-n** [comment]
Sorry. Didn't see your message. Will get back to you on this. Its been a while that I worked on it.

**Comment by chinmaya-n** [comment]
Hi @jaimeperez ,

I'm still getting the following errors (in `simplesamlphp.log`) that I originally posted and I'm currently using `php:7.3-apache` docker image with SSP `1.17.6` version. I'll need to remove all my customizations (like metadata and few dozen configurations) to blame PHP as the source of the issue. I'll try to reproduce this with a clean SSP setup on `php:7.3-apache` image and report it.

```
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] SimpleSAML\Error\Exception: Error 2 - session_name(): Cannot change session name when headers already sent at /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:72
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Backtrace:
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 8 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 7 [builtin] (session_name)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 6 /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:72 (SimpleSAML\SessionHandlerPHP::__construct)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 5 /var/simplesamlphp/lib/SimpleSAML/SessionHandler.php:134 (SimpleSAML\SessionHandler::createSessionHandler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 4 /var/simplesamlphp/lib/SimpleSAML/SessionHandler.php:41 (SimpleSAML\SessionHandler::getSessionHandler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 3 /var/simplesamlphp/lib/SimpleSAML/Session.php:336 (SimpleSAML\Session::getSession)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 2 /var/simplesamlphp/lib/SimpleSAML/Session.php:268 (SimpleSAML\Session::getSessionFromRequest)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 1 /var/simplesamlphp/lib/SimpleSAML/Logger.php:284 (SimpleSAML\Logger::shutdown)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 0 [builtin] (N/A)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] SimpleSAML\Error\Exception: Error 2 - session_id(): Cannot change session id when headers already sent at /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:192
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Backtrace:
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 6 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 5 [builtin] (session_id)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 4 /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:192 (SimpleSAML\SessionHandlerPHP::getCookieSessionId)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 3 /var/simplesamlphp/lib/SimpleSAML/Session.php:340 (SimpleSAML\Session::getSession)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 2 /var/simplesamlphp/lib/SimpleSAML/Session.php:268 (SimpleSAML\Session::getSessionFromRequest)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 1 /var/simplesamlphp/lib/SimpleSAML/Logger.php:284 (SimpleSAML\Logger::shutdown)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 0 [builtin] (N/A)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] SimpleSAML\Error\Exception: Error 2 - ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:244
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Backtrace:
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 6 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 5 [builtin] (ini_set)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 4 /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:244 (SimpleSAML\SessionHandlerPHP::loadSession)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 3 /var/simplesamlphp/lib/SimpleSAML/Session.php:352 (SimpleSAML\Session::getSession)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 2 /var/simplesamlphp/lib/SimpleSAML/Session.php:268 (SimpleSAML\Session::getSessionFromRequest)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 1 /var/simplesamlphp/lib/SimpleSAML/Logger.php:284 (SimpleSAML\Logger::shutdown)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 0 [builtin] (N/A)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Error loading session: Disabling PHP option session.use_cookies failed.
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] SimpleSAML\Error\Exception: Error 2 - session_id(): Cannot change session id when headers already sent at /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:192
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Backtrace:
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 7 /var/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 6 [builtin] (session_id)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 5 /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:192 (SimpleSAML\SessionHandlerPHP::getCookieSessionId)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 4 /var/simplesamlphp/lib/SimpleSAML/Session.php:170 (SimpleSAML\Session::__construct)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 3 /var/simplesamlphp/lib/SimpleSAML/Session.php:424 (SimpleSAML\Session::useTransientSession)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 2 /var/simplesamlphp/lib/SimpleSAML/Session.php:277 (SimpleSAML\Session::getSessionFromRequest)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 1 /var/simplesamlphp/lib/SimpleSAML/Logger.php:284 (SimpleSAML\Logger::shutdown)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] 0 [builtin] (N/A)
Oct 24 14:48:31 simplesamlphp ERROR 172.17.0.1 [TR7e2fb8a2] Cannot load or create session: Disabling PHP option session.use_cookies failed.
```

**Comment by berglh** [comment]
I'm running 1.18.1-rc2 and PHP Version 7.3.11, and still receiving errors with `SessionhandlerPHP.php`. I am able to authenticate correctly, just when I return to the site to execute a different PHP script, it fails. Things improved a lot over 1.17.x, but this is still lurking around and (I think), related to this problem.

When I revert PHP to version 7.1.33, everything is just dandy. Should I start a new issue?

```
Fatal error: Uncaught SimpleSAML\Error\Exception: Cannot load PHP session with a specific ID. 
in /var/www/simplesamlphp-1.18.0-rc2/lib/SimpleSAML/SessionHandlerPHP.php:265 Stack trace: 
#0 /var/www/simplesamlphp-1.18.0-rc2/lib/SimpleSAML/Session.php(344): 
SimpleSAML\SessionHandlerPHP->loadSession('b19323f68551bad...') #1 
/var/www/simplesamlphp-1.18.0-rc2/lib/SimpleSAML/Session.php(259): 
SimpleSAML\Session::getSession() #2 /var/www/simplesamlphp-1.18.0-rc2/lib/SimpleSAML/Auth/Simple.php(51): 
SimpleSAML\Session::getSessionFromRequest() #3 /var/www/auth/index.php(16): 
SimpleSAML\Auth\Simple->__construct('default-sp') #4 {main} thrown in 
/var/www/simplesamlphp-1.18.0-rc2/lib/SimpleSAML/SessionHandlerPHP.php on line 265
```
