### ISSUE TITLE
The module 'le.php' was either not found, or wasn't enabled

### ISSUE THREAD

**Issue by MarkelovSergey** [simplesamlphp/simplesamlphp#1103]
**Describe the bug**
Hi, I am trying to update SimplSamPnp 1.15.0 to the current version according to the instructions https://simplesamlphp.org/docs/stable/simplesamlphp-install.
An error occurs - "http: //site.com/simplesaml/module.php/core/frontpage_welcome.php 'could not be found. The module 'le.php' was either not found, or wasn't enabled"

**To Reproduce**
1. Download Latest stable version (1.17.2)
2. cd /var/simplesamlphp-1.17.2 rm -rf config metadata cp -rv ../simplesamlphp/config config cp -rv ../simplesamlphp/metadata metadata
3. When I open the page(https://site.com/simplesaml) I get an error:
The module 'le.php' was either not found, or wasn't enabled

**Screenshots or logs**
Apr 24 16:03:28 simplesamlphp ERROR [6bca6e5443] SimpleSAML\Error\NotFound: The requested page 'https://site.com/simplesaml/module.php/core/frontpage_federation.php' could not be found. The module 'le.php' was either not found, or wasn't enabled.
Apr 24 16:03:28 simplesamlphp ERROR [6bca6e5443] Backtrace:
Apr 24 16:03:28 simplesamlphp ERROR [6bca6e5443] 1 /var/www/simplesamlphp/lib/SimpleSAML/Module.php:154 (SimpleSAML\Module::process)
Apr 24 16:03:28 simplesamlphp ERROR [6bca6e5443] 0 /var/www/simplesamlphp/www/module.php:9 (N/A)
Apr 24 16:03:28 simplesamlphp ERROR [6bca6e5443] Error report with id 8edaddee generated.

**Comment by tvdijen** [comment]
Are you performing some kind of URL rewriting in Apache?

**Comment by MarkelovSergey** [comment]
I use nginx. The configuration did not change. My configuration:location ^ ~ / simplesaml {alias /var/www/simplesamlphp/www;          location ~ ^ (? <prefix> / simplesaml) (? <phpfile>. +? \. php) (? <pathinfo> /.*)? $ {             include fastcgi_params;             fastcgi_pass unix: /var/run/php/php7.2-fpm.sock;             fastcgi_param SCRIPT_FILENAME $ document_root $ phpfile;             fastcgi_param PATH_INFO $ pathinfo if_not_empty;         }}24.04.2019, 17:38, "Tim van Dijen" <notifications@github.com>:Are you performing some kind of URL rewriting in Apache?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением Маркелов С.А.

**Comment by tvdijen** [comment]
I think you're somehow messing up your PATH_INFO with your Nginx config..
What happens if you follow the [example](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-install.md#configuring-nginx) Nginx config regarding the fastgci-params??

**Comment by tvdijen** [comment]
A similar case was just solved on our [mailinglist](https://groups.google.com/forum/#!forum/simplesamlphp) by fixing the baseurlpath-setting in `config.php`.. This is also something we can check on your end! What is the value of that setting?

**Comment by tvdijen** [comment]
Any news on your end @MarkelovSergey ?

**Comment by MarkelovSergey** [comment]
Hello, there were urgent tasks, so I had to postpone this task. It is not solved, I will definitely return to it.

**Comment by pricejh** [comment]
I am also having this problem, trying to update from 1.15.3 to 1.17.2.  The problem arises simply by replacing 1.15.3 with 1.17.2, making no other changes.  I have tried tvdijen's suggestions -- my baseurl path setting is 'simplesaml/', (the default), which has not changed and worked previously. The problem occurs when using the example Nginx config.  FWIW, first encountered the problem running homebrew installations of php 7.1 and nginx 1.15.1 on a Macbook Pro running 10.14.5 macOS.   Also see the problem using php 7.3 and nginx 1.15.2 via Docker containers.  Any suggestions greatly appreciated!

**Comment by jaimeperez** [comment]
Thanks for the feedback @pricejh!

What happens if your set `baseurlpath` properly to the canonical URL of your deployment (e.g. `https://site.com/simplesaml/`)?

**Comment by pricejh** [comment]
Thanks for getting back to me. I see the same behavior with the canonical URL.

Sent from my iPad

On May 29, 2019, at 1:08 AM, Jaime Pérez Crespo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback @pricejh<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpricejh&data=02%7C01%7C%7C5b151b1bc90140b273b008d6e40ccb0e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636947140922594855&sdata=ZYXdVcV8%2F1aTYVYUwqGt4uTxcU8mNE3%2Fv1a0EWjkoCA%3D&reserved=0>!

What happens if your set baseurlpath properly to the canonical URL of your deployment (e.g. https://site.com/simplesaml/)?

**Comment by tvdijen** [comment]
From what I see in this case and others is that Symfony's `$request->getPathInfo()` has a different behaviour on Nginx compared to Apache.. Perhaps all we have to do is update the example configuration for Nginx to work with Symfony... I'll try and look into this a bit more and see if I can find similar issues.

**Comment by tvdijen** [comment]
@pricejh what version of Symfony is installed? Or you on 3.4 or on 4.0?
In former case, could you upgrade it to 4.0?
In the latter case, could you try downgrading it to 3.4?

**Comment by pricejh** [comment]
Hmm, to my knowledge, I'm not using Symfony at all, unless it's being installed by something behind the scenes.  How would I check?  I've got the issue with Mac (using Homebrew for PHP) and on Docker containers (based on CentOS 7)

**Comment by mschwager** [comment]
Are you missing the `SCRIPT_NAME`? When I was initially looking into this, here was the `nginx.conf` I came up with: https://github.com/mschwager/docker-simplesamlphp/blob/master/configuration/nginx.conf

One thing I noticed was the `SCRIPT_NAME` must be prepended with the `baseurlpath`, e.g.

```
...
# Must be prepended with the baseurlpath
fastcgi_param SCRIPT_NAME /simplesaml$phpfile;
...
```

**Comment by pricejh** [comment]
Thanks for the suggestion, I appreciate the effort.
I had ...

`fastcgi_param SCRIPT_FILENAME $document_root$phpfile;`

changed it to ...

fastcgi_param SCRIPT_NAME /simplesaml$phpfile;`

then restarted PHP and Nginx.   Both worked for 1.16.3, but neither worked for 1.17.2. (This was on my Mac, will try on Docker at work tomorrow, just in case.)

Thanks again.

**Comment by pricejh** [comment]
I should clarify that when I say 'neither worked', that in both cases I received the same error as before. I'll try using Apache instead of Nginx in the the affected Docker container and see if that resolves things.  If it does, that will isolate the problem to Nginx...

**Comment by rroblik** [comment]
Hi @pricejh ,

I had the same probleme, please see my working nginx configuration:

```conf
location /simplesaml {
		alias /www/mysite/vendor/simplesamlphp/simplesamlphp/www;
		
		location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
			include fastcgi_params;
			fastcgi_pass $fastcgi_pass;
			fastcgi_param SIMPLESAMLPHP_CONFIG_DIR /www/mysite/simplesaml_config_dir;
			fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
			fastcgi_param SCRIPT_NAME /simplesaml$phpfile;
			fastcgi_param PATH_INFO $pathinfo if_not_empty;
		}
	}
```

Note that I set the `SIMPLESAMLPHP_CONFIG_DIR ` outside of the `vendor` folder, as it's a best practice.

Best regards

**Comment by pricejh** [comment]
Hat tip to rroblik and to mschwager, this is working for me now both on my Mac and in Docker images.  Below is the before and after of my (Docker) Nginx config. Briefly, changed the inner 'location' to that suggested by rroblik, and added SCRIPT_NAME as suggested by mschwager.   The 'before' works with 1.15.4 and 1.16.3 but not with 1.17.2, the 'after' works with all three.  (The 'php1' bit of the `fastcgi_pass` variable is a separate Docker container running php 7.1.)  Thanks!

BEFORE --

	location ^~ /simplesaml {
		index index.php;
		alias /sso/simplesamlphp/www/;
		location ~ ^.*/simplesaml/(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
			include fastcgi_params;
			fastcgi_pass php1:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
			fastcgi_param PATH_INFO       $pathinfo if_not_empty;
		}
	}

AFTER -- 

	location ^~ /simplesaml {
		index index.php;
		alias /sso/simplesamlphp/www/;
		location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
			include fastcgi_params;
			fastcgi_pass php1:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
			fastcgi_param SCRIPT_NAME /simplesaml$phpfile;
			fastcgi_param PATH_INFO	   $pathinfo if_not_empty;
		}
	}

**Comment by tvdijen** [comment]
Finally results @pricejh !! We will change this in our documentation
