### ISSUE TITLE
Post-Authentication error message logged

### ISSUE THREAD

**Issue by htto** [simplesamlphp/simplesamlphp#1312]
**Describe the bug**
After a successful login the error log contains the following line
`ERR [b9eda02eeb] Missing default-enable or default-disable file for the module `
(note the missing module name that should be following).

**To Reproduce**
1. (Probably) configure new TWIG UI
2. SSO-Login
3. Enter valid credentials
4. See error in log

**Expected behavior**
No error logged

**Screenshots or logs**
Manually inserted stacktrace generation if module is empty:
```
simplesamlphp-idp ERR [b9eda02eeb] Missing default-enable or default-disable file for the module
#0 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php(109): SimpleSAML\Module::isModuleEnabledWithConf(NULL, Array)
#1 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/TemplateLoader.php(70): SimpleSAML\Module::isModuleEnabled(NULL)
#2 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php(260): SimpleSAML\XHTML\TemplateLoader::getModuleTemplateDir(NULL)
#3 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php(290): SimpleSAML\XHTML\Template->setupTwigTemplatepaths()
#4 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php(157): SimpleSAML\XHTML\Template->setupTwig()
#5 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php(1309): SimpleSAML\XHTML\Template->__construct(Object(SimpleSAML\Configuration), 'post.php')
#6 /var/www/sso-idp/vendor/simplesamlphp/saml2/src/SAML2/Compat/Ssp/Container.php(74): SimpleSAML\Utils\HTTP::submitPOSTData('http://localhos...', Array)
#7 /var/www/sso-idp/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php(48): SAML2\Compat\Ssp\Container->postRedirect('http://localhos...', Array)
#8 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/modules/saml/lib/IdP/SAML2.php(114): SAML2\HTTPPost->send(Object(SAML2\Response))
#9 [internal function]: SimpleSAML\Module\saml\IdP\SAML2::sendResponse(Array)
#10 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/IdP.php(290): call_user_func(Array, Array)
#11 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/IdP.php(337): SimpleSAML\IdP::postAuthProc(Array)
#12 [internal function]: SimpleSAML\IdP::postAuth(Array)
#13 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php(246): call_user_func(Array, Array)
#14 [internal function]: SimpleSAML\Auth\Source::loginCompleted(Array)
#15 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php(159): call_user_func(Array, Array)
#16 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/modules/core/lib/Auth/UserPassBase.php(329): SimpleSAML\Auth\Source::completeAuth(Array)
#17 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/modules/core/www/loginuserpass.php(84): SimpleSAML\Module\core\Auth\UserPassBase::handleLogin('_5d0002ca576599...', 'user', 'pass')
#18 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php(254): require('/var/www/sso-id...')
#19 /var/www/sso-idp/vendor/simplesamlphp/simplesamlphp/www/module.php(10): SimpleSAML\Module::process()
#20 {main}
```
Adding some error_logs to SimpleSAML/XHTML/Template `error_log('findModuleAndTemplateName: ' . $template . ' -> ' . implode(',', $x));`:
non-erroring
```
findModuleAndTemplateName: core:loginuserpass.tpl.php -> core,loginuserpass.tpl.php
findModuleAndTemplateName: custommod:customtheme -> custommod,customtheme
findModuleAndTemplateName: core:loginuserpass.twig -> core,loginuserpass.twig
```
vs. erroring
```
findModuleAndTemplateName: post.php -> ,post.php
findModuleAndTemplateName: custommod:customtheme -> custommod,customtheme
findModuleAndTemplateName: post.twig -> ,post.twig
```
Looks like the missing module-prefix for post.twig is the problem (since the error produces right after access to post.twig but not post.php...

**Additional context**
Apparently `Template::setupTwigTemplatepaths()` is the culprit:
```
if ($this->module && $this->module != 'core') {                                                                         
    $templateDirs[] = [$this->module => TemplateLoader::getModuleTemplateDir($this->module)];                           
}                                                                                                                       
if ($this->theme['module']) {                                                                                           
    try {                                                                                                               
        $templateDirs[] = [                                                                                             
            $this->theme['module'] => TemplateLoader::getModuleTemplateDir($this->theme['module'])                      
        ];                                                                                                              
        $templateDirs[] = ['__parent__' => TemplateLoader::getModuleTemplateDir($this->module)];                        
    } catch (\InvalidArgumentException $e) {                                                                            
        // either the module is not enabled or it has no "templates" directory, ignore                                  
    }                                                                                                                   
}     
```
The first call to `TemplateLoader::getModuleTemplateDir($this->module)` is guarded by a `$this->module`-check, while the second one is only guarded by a `$this->theme['module']`-check. Caching the result of `TemplateLoader::getModuleTemplateDir($this->module)` instead of calling it twice would probably be nice as well.

**Comment by tvdijen** [comment]
Why not just do what the error says and enable the module you're trying to use?

**Comment by htto** [comment]
So what module is it then? It is empty. `$this->module` is NULL for post.twig, thus the unguarded getModuleTemplateDir(NULL) emits the error because there's no module to default-enable/default-disable. Why would one guard against `$this->module` in one place but not seven lines below?

**Comment by tvdijen** [comment]
In this case I'm pretty sure it's your custommod-module that needs to be enabled.. I agree that the error message could be improved

**Comment by tvdijen** [comment]
Ah, I'm starting to understand what's happening now..  We're not catching the null-case correctly (but this was fixed on master).. Do I understand correctly that the IDP is working just fine, except for this error being silently logged on every authentication?

**Comment by htto** [comment]
It's still not properly handled in master (I checked before opening, yesterday): https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/XHTML/Template.php#L238

All modules are enabled/disabled as needed, the custom module working as intended also. Yes, it still works as expected, but when monitoring the log for SSO-errors, this one pops up and pollutes the log more the more users log in. I'd given it low priority, but haven't found such setting for issues.


Anyway, looks like it's not the redirection that's the problem, but the theming. I recreated the issue with plain SimpleSAMLphp. Following the theming-guide with a theme mymodule:fancytheme, 
it is enough to add the directory `modules/mymodule/templates` giving the following structure
```
modules/mymodule/
modules/mymodule/templates
modules/mymodule/themes
modules/mymodule/themes/fancytheme
modules/mymodule/default-enable
```
Then enabling twig theming and using the fancytheme is enough to trigger the error after each login. Though, I'm not quite sure why `$this->module` doesn't get properly populated with `mymodule`, since the added `templates` folder resides in the module.

I initially ran into the issue, probably because our custom module has auth source, auth filter, locales and theming in one, though I haven't found a word that this isn't allowed.

**Comment by jaimeperez** [comment]
Hi @htto!

You are absolutely true, this is a bug. We should never be passing `null` to `TemplateLoader::getModuleTemplateDir()`. I believe this stems from #1174.

Would you mind applying this patch and tell me if everything is fine then?

```patch
diff --git a/lib/SimpleSAML/XHTML/Template.php b/lib/SimpleSAML/XHTML/Template.php
index 24986d32f..25371a924 100644
--- a/lib/SimpleSAML/XHTML/Template.php
+++ b/lib/SimpleSAML/XHTML/Template.php
@@ -250,14 +250,15 @@ class Template extends Response
         $loader = new TemplateLoader();
         $templateDirs = $this->findThemeTemplateDirs();
         if ($this->module && $this->module != 'core') {
-            $templateDirs[] = [$this->module => TemplateLoader::getModuleTemplateDir($this->module)];
+            $modDir = TemplateLoader::getModuleTemplateDir($this->module);
+            $templateDirs[] = [$this->module => $modDir];
+            $templateDirs[] = ['__parent__' => $modDir];
         }
         if ($this->theme['module']) {
             try {
                 $templateDirs[] = [
                     $this->theme['module'] => TemplateLoader::getModuleTemplateDir($this->theme['module'])
                 ];
-                $templateDirs[] = ['__parent__' => TemplateLoader::getModuleTemplateDir($this->module)];
             } catch (\InvalidArgumentException $e) {
                 // either the module is not enabled or it has no "templates" directory, ignore
             }
```

**Comment by ghalse** [comment]
Tagging @dmcoetzee to look at this, since he may get to it sooner than I will at the moment.

**Comment by jaimeperez** [comment]
So, after confirming that the patch works, and it doesn't break the functionality added in #1174, I've applied it now to `master`, `simplesamlphp-1.19` and `simplesamlphp-1.18`. Thanks for reporting it @htto, and for the help testing @dmcoetzee and @ghalse!

**Comment by htto** [comment]
> Hi @htto!
> 
> You are absolutely true, this is a bug. We should never be passing `null` to `TemplateLoader::getModuleTemplateDir()`. I believe this stems from #1174.
> 
> Would you mind applying this patch and tell me if everything is fine then?
> 

Hey,

Sorry I haven't gotten back to this any earlier. But I still wanted to let you know: Applying the patch does indeed resolve the error message -- even on SSP 1.18.5.

Thanks for looking into this and fixing :)

**Comment by jaimeperez** [comment]
Thanks for the feedback @htto! This is now in the 1.18.6 release my colleague Olav just released.
