### ISSUE TITLE
Setting host in saml20-idp-hosted breaks IdP metadata for e.g. md:SingleSignOnService

### ISSUE THREAD

**Issue by msalle** [simplesamlphp/simplesamlphp#1922]
**Specifics of your environment**
1. Running a proxy
2. SimpleSAMLphp: 2.1.1
3. PHP: 8.0
4. Platform: Linux
5. Webserver: Apache

**Describe the bug**
In SSP2.1.1 the md:SingleLogoutService and md:SingleSignOnService Location in the IdP metadata is set to the wrong URL:
My apache (using `Alias`) is configured to have SSP run in a subdirectory (`/somepath`). I have the same setup as `baseurlpath` in config.php (`somepath/`).
In addition I have configured an overrideHost (`host`) in my metadata/saml20-idp-hosted.php, let's call it idp.example.org.

The new commit https://github.com/simplesamlphp/simplesamlphp/commit/b6a05a831accd4fbe62c22ff7d3c41c319f761b2 replaces the hostname including `/somepath` with the overridden hostname, which results in an incorrect  md:SingleLogoutService and md:SingleSignOnService Location.

**To Reproduce**
1. configure Apache to map `/somepath` to SSP's public directory, set the same (with slash at the end: `somepath/`) as `baseurlpath` in config.php
2. configure a `host` (i.e. overrideHost) in metadata/saml20-idp-hosted.php, set to e.g. idp.example.org
3. request https://idp.example.org/somepath/module.php/saml/idp/metadata
4. Location in both  md:SingleLogoutService  and md:SingleSignOnService now has the `/somepath` part stripped out.
    (Note that the errorURL in md:IDPSSODescriptor does contain it correctly)

I can "fix" it by setting my `host` in metadata/saml20-idp-hosted.php to include the `/somepath` part but that is an odd solution.

**Expected behavior**
I would expect the correct Location, including the `/somepath` path, reproducing the old behaviour.

**Additional context**
Just before the str_replace I have the following values:
- `$httpUtils->getSelfURLHost()`: `https://idp.example.org`
- `$httpUtils->getSelfHostWithPath()`: `idp.example.org/somepath`
- `$httpUtils->getSelfHost()`: `idp.example.org`
- `$config->getBasePath()`: `/somepath/`
So the str_replace is effectively:
`str_replace(://idp.example.org/somepath/, ://idp.example.org/, https://idp.example.org/somepath/);`

**Comment by tvdijen** [comment]
The `host` variable is supposed to include the alias used in Apache.
This way you can have multiple aliases, and multiple IdP's under the same hostname.

**Comment by msalle** [comment]
I understand the reasons, but this is a breaking change between 2.0 and 2.1 (just checked that 2.0.8 still has the old code, 2.1.0 has the new code). At the very least I would say:
- it should be clearly mentioned in [upgrade notes](https://simplesamlphp.org/docs/2.1/simplesamlphp-upgrade-notes-2.1).
- be clear from the [documentation](https://simplesamlphp.org/docs/2.1/simplesamlphp-reference-idp-hosted.html) which under `host` still says "The hostname for this IdP."
- be clear from the [template](https://github.com/simplesamlphp/simplesamlphp/blob/v2.1.0/metadata/saml20-idp-hosted.php.dist#L11) which still says "The hostname of the server (VHOST)"
- and be clear from the [code](https://github.com/simplesamlphp/simplesamlphp/blob/v2.1.0/src/SimpleSAML/Metadata/MetaDataStorageHandler.php#L86) which still says "Hostname to use in the URLs".

I would have very much preferred if there would have been a new option `override_baseurl` or something like that, which would have preference over `host`, such that you could keep the backwards compatibility.

**Comment by tvdijen** [comment]
Can you verify that the issue was resolved in later 2.1.x versions?

**Comment by msalle** [comment]
Apologies for the delay in answering, too many things came up.
I should have read your comment better since I've just upgraded to 2.2.1 not to 2.1.5. Hence I still see the same behaviour, but that makes sense, since I see it's only fixed in the 2.1.X branch:
[line 106 in v2.2.1](https://github.com/simplesamlphp/simplesamlphp/blame/v2.2.1/src/SimpleSAML/Metadata/MetaDataStorageHandler.php#L106) versus [line 106 v2.1.5](https://github.com/simplesamlphp/simplesamlphp/blame/v2.1.5/src/SimpleSAML/Metadata/MetaDataStorageHandler.php#L106)

**Comment by tvdijen** [comment]
I just ported the fix to the 2.2 branch. It will be part of the v2.2.2 release whenever that is.

**Comment by msalle** [comment]
Great, many thanks!
