### ISSUE TITLE
Session problems!

### ISSUE THREAD

**Issue by urban-1** [simplesamlphp/simplesamlphp#365]
Hi all,

I am very new to SAML so I might be doing things wrong. I have described my problem at SO: http://stackoverflow.com/questions/36655953/simplesamlphp-unable-to-find-the-current-binding. (I have a local copy in case it gets closed...)

All the above errors seem to appear randomly due to faulty state of some sort...  I am using (and modifying) `$_SESSION` in my application and I have noticed that it is getting changed/replaced by SSP. If I remove all the code that changes session (including `_start()`/`_destroy()`), login and logout works without crashing. Is there a specific way I should be handling the session?

I have tried to set the `store.type` to `sql`, in which case, an sqlite file is created but SSP always comes back with "NO STATE" error. Also note that I can see apache segfaulting in the logs

My site login logic:

```
        // If loaded do not load again (depending on force value)
        if (isset($_SESSION['user']['realname']) && !$force) {
           return true;
        }
        
        // 1st check and use SAML
        if (!isset($_SESSION['user']['username']) ) {
            // Try SAML here
            error_log("initUser::checking SAML");
            static::doSAMLAuth();
        }
        
        // 2nd check and FAIL
        if (!isset($_SESSION['user']['username']) ) {
            error_log("Session not loaded???");
            return false;
        }
        
        // Update the SESSION
        
        // LDAP will update stuff!
        $ldap = new LDAP("AD");
        error_log("initUser::Quering LDAP");
        $ldapUser = $ldap->getUser($_SESSION['user']['username']);`
        $_SESSION['user'] = $ldap->ldapUser2Web($ldapUser);
```

and the SSP authentication:

```
       $auth = new SimpleSAML_Auth_Simple(SSAMLSP);
        
        // This should do the correct redirect
        error_log("doSAML::requireAuth");
        $auth->requireAuth();
        
        error_log("doSAML::isAuthenticated");
         
        // Setup session for this SP
        $ad = $auth->getAuthData("saml:sp:NameID");
        
        $_SESSION['user']['username'] = $ad["Value"];
```

Any help would be appreciated

Andreas

Working on:
 RHEL 7
 PHP 5.4.16
 Apache 2.4
 simplesamlphp 1.14.2

**Comment by jaimeperez** [comment]
Hi @urban-1!

This is a duplicate of #224 and #349. It has been already fixed and the fix will be available in the next release (about to come out). Check the related issues for more information on how to use PHP sessions in both your application and SimpleSAMLphp at the same time from now on.

**Comment by urban-1** [comment]
@jaimeperez Do I have to apply the mentioned patch? Is master stable enough to use?

**Comment by jaimeperez** [comment]
Hi @urban-1!

No, the patch was unfortunately not enough to solve all the issues with the PHP session handler. However, we just released `1.14.3` today, including the fix for this issue 😉 

Master is usually pretty stable (we try hard at least), but of course that doesn't mean we don't make mistakes sometimes and break things, so I'd recommend you to stick to stable releases unless you really need something.

**Comment by urban-1** [comment]
Cool, thanks for the quick reply. I will upgrade and let you know

**Comment by urban-1** [comment]
Hey, unfortunately I am still getting the same error(s) and apache keeps on segfaulting. I checked the new code and `session_write_close()` is being called but the the session ID remains the same. I do call `$session->cleanup();` but the session still shows "SimpleSAMLphp_SESSION" entry:

```
        error_log("SSID: " . session_id(). " - ". session_name());
        
        $auth = new SimpleSAML_Auth_Simple(SSAMLSP);
        
        // This should do the correct redirect
        error_log("doSAML::requireAuth");
        $auth->requireAuth();
        
        error_log("doSAML::isAuthenticated");
         
        // Setup session for this SP
        $ad = $auth->getAuthData("saml:sp:NameID");
        
        $session = SimpleSAML_Session::getSessionFromRequest();
        $session->cleanup();
        
        error_log("FINAL SSID: " . session_id(). " - ". session_name());
        
        $_SESSION['user']['username'] = $ad["Value"];
        error_log(print_r($_SESSION, true));
```

Also, tried to shift the `store.type` to `sql` but as before, I get a "no state" error every time. I will try to debug this but I am kinda lost atm...

**Comment by jaimeperez** [comment]
Hi!

The segfaults might be related to #293. If you are experiencing them often, those could lead to the sessions not being properly saved to the backend (`sql` in this case) and causing a `NO_STATE` error. The only way to fix that is to upgrade PHP to some version more up to date, as the segfaults are due to a bug in PHP itself.

Regarding the PHP session not being recovered, can you provide the entire script you are using to test? What's its output? Did you try the script provided in #224? Did it work?

**Comment by urban-1** [comment]
I run the script from #224. If I do not set the name of/rename the session I get:

```
Session Name: PHPSESSID

Session ID: 4158fa896b4541702e843e370bb9ed4e

Session contents: 
array (
  'SimpleSAMLphp_SESSION' => '... (the serialized session without errors)...',
  'foo' => 'bar',
  'attributes' => 
  array (
  ),
)
```

Note that empty attributes is correct (no claims). Now, if I do set the session name I get:

```
SimpleSAML_Error_NoState: NOSTATE
Backtrace:
2 /apps/apache/ssl/simplesamlphp-1.14.3/lib/SimpleSAML/Auth/State.php:263 (SimpleSAML_Auth_State::loadState)
1 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/www/sp/saml2-acs.php:78 (require)
0 /apps/apache/ssl/simplesamlphp-1.14.3/www/module.php:127 (N/A)
```

The whole script:

```
<?php

// configure according to your needs
$path = '/';
$host = '';
$secure = true ;
$session_name = 'SAR';
$ssproot = '/var/www/html/ssl/simplesamlphp-1.14.3/';

// create our own session
session_set_cookie_params(0, $path, $host, $secure);
session_name($session_name);
session_start();
$id = session_id();

// if our session was not initialized or there's no attributes, require auth
if (!array_key_exists('foo', $_SESSION) || !array_key_exists('attributes', $_SESSION)) {
    $_SESSION['foo'] = 'bar';
    include $ssproot.'www/_include.php';
    $auth = new SimpleSAML_Auth_Simple('sar-dev-sp');
    $auth->requireAuth();
    $attributes = $auth->getAttributes();

    // restore our own session
    $session = SimpleSAML_Session::getSessionFromRequest();
    $session->cleanup();

    // save the attributes to the session
    $_SESSION['attributes'] = $attributes;

    // test that SSP's session is still working
    $session->doLogout("sar-dev-sp");
}

// print details about *our* session
header("Content-Type: text/plain; charset=utf-8");
echo "Session Name: ".session_name()."\n\n";
echo "Session ID: ".session_id()."\n";
echo "\nSession contents: \n".var_export($_SESSION, true);
?>
```

Is there any particular settings I should have to rename session? (Either in php.ini or config.php).

**Comment by jaimeperez** [comment]
Yes, you should give your SimpleSAMLphp cookie its own name. If you don't have one configured, it will take the default, which could lead to trouble. Did you set the `session.phpsession.cookiename` in `config/config.php`? In that case, to what value?

In any case, if you are using the defaults in SimpleSAMLphp and setting a session name in the script, that should definitely not lead to a `NO_STATE` error. I'll have to look into that.

Enjoy the beers! 🍻

**Comment by urban-1** [comment]
Morning @jaimeperez 

This works!!! It would have taken me a million years to sort it out :). Note that both the application `session_name` and the `session.phpsession.cookiename` must be set to non-default values in order to work on my setup.

I am happy with how it works now but I have two more questions:

1. I sometimes get the following error.I assume it is because I login and out too fast and the IdP says "no" at some point:

    ```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /apps/apache/ssl/simplesamlphp-1.14.3/www/module.php:170 (N/A)
Caused by: sspmod_saml_Error: Responder
Backtrace:
3 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/lib/Message.php:392 (sspmod_saml_Message::getResponseError)
2 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/lib/Message.php:499 (sspmod_saml_Message::processResponse)
1 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/www/sp/saml2-acs.php:120 (require)
0 /apps/apache/ssl/simplesamlphp-1.14.3/www/module.php:127 (N/A)
    ```

2. Which would be the correct way to implement logout:
    ```php
$auth = new SimpleSAML_Auth_Simple(SSAMLSP);
$auth->logout("$url/loggedout.php");
    ```
works and I can see the redirect to the IdP. However, in the test script we used the session:

    ```php
$session = SimpleSAML_Session::getSessionFromRequest();
$session->doLogout("sar-dev-sp");
header("Location: $url/loggedout.php");
    ```
which also works, but I do not see the redirection. I assume it cleans the SSP session data but it does not logout from the IdP - which I am not sure if it is needed. The session works a lot better for me since the first one leads to `ACSPARAMS` and `SLOSERVICEPARAMS` errors with the following steps:
    1. Starting with "This page can’t be displayed"
    2. Refresh (F5)
    3. May produce a `PHP Notice:  Undefined property: DOMDocument::$x�j5� in �d�5� on line 352` which I think is the PHP bug we talked about (this is actually refering to `lib/SimpleSAML/Session.php` line 352)
    4. SSP error page

I suspect that the last problem is related to #293 and has nothing to do with SSP...

Anyway, thank you very very much for your help! Let me know if you want me to run any other tests

**Comment by jaimeperez** [comment]
Morning!

Glad you got it to work! Did you try calling `session_name()` in your app, and let SimpleSAMLphp using the default session, and the other way around? Of course, the application and SimpleSAMLphp need to use different session names, since that's what determines the name of the cookie set. Different cookies mean different session IDs, and therefore different sessions overall. But the name you use (whether that's the default or not) should be irrelevant, provided both use different names.

Now, regarding your two questions:

>1. I sometimes get the following error.I assume it is because I login and out too fast and the IdP says "no" at some point:
>
>```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /apps/apache/ssl/simplesamlphp-1.14.3/www/module.php:170 (N/A)
Caused by: sspmod_saml_Error: Responder
Backtrace:
3 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/lib/Message.php:392 (sspmod_saml_Message::getResponseError)
2 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/lib/Message.php:499 (sspmod_saml_Message::processResponse)
1 /apps/apache/ssl/simplesamlphp-1.14.3/modules/saml/www/sp/saml2-acs.php:120 (require)
0 /apps/apache/ssl/simplesamlphp-1.14.3/www/module.php:127 (N/A)
    ```

That's an error you are getting from the IdP. Aren't you getting any more information in the error page or in the log files? You could also try to replicate the error while monitoring the SAML exchange with SAML tracer so that you can see the SAML response you are getting posted.

>2. Which would be the correct way to implement logout:
>    ```php
$auth = new SimpleSAML_Auth_Simple(SSAMLSP);
$auth->logout("$url/loggedout.php");
    ```
>works and I can see the redirect to the IdP. However, in the test script we used the session:

>    ```php
$session = SimpleSAML_Session::getSessionFromRequest();
$session->doLogout("sar-dev-sp");
header("Location: $url/loggedout.php");
    ```

The first one. As you have noticed, that's the way to trigger a single logout. The latter does only log out the local session, not informing the IdP (nor any other service providers you might be logged into). I only added that in the test script to make sure that if we try to use SimpleSAMLphp's session after cleaning up, the session gets loaded again, but you should never mess directly with the session.

>The session works a lot better for me since the first one leads to `ACSPARAMS` and `SLOSERVICEPARAMS` errors with the following steps:

That could happen if you access the endpoints directly, which you shouldn't do.

>    1. Starting with "This page can’t be displayed"

How do you reach there?

>    2. Refresh (F5)
>    3. May produce a `PHP Notice:  Undefined property: DOMDocument::$x�j5� in �d�5� on line 352` which I think is the PHP bug we talked about (this is actually refering to `lib/SimpleSAML/Session.php` line 352)

That sounds really weird. Binary data as the name of property? 😟 

>    4. SSP error page

What does the error say? Any logs?

>I suspect that the last problem is related to #293 and has nothing to do with SSP...

No, I don't think so. That problem was causing segfaults when PHP finishes its execution and SimpleSAMLphp tries to save the session if it was modified. If that was the case, you should be seeing segfaults in your server's log when this error appears. And in any case, it's not something related to logout itself, but to session handling, so if this was the issue you would be experiencing errors all over the place, not only when trying to perform a single logout...

**Comment by urban-1** [comment]
I am testing by login/out fast. The logout completes successfully but the next login might fail. On failure there are few different cases:

- last test got stuck on the url `.../saml/module.php/saml/sp/saml2-acs.php/sar-dev-sp` with no error in the logs. A refresh leads to`ACSPARAMS`error.
- Sometimes the logout seems to be called twice:

    ```
[20-Apr-2016 12:49:07 Europe/London] Logout: STS
[20-Apr-2016 12:49:07 Europe/London] Logout: STS
    ```

    the code in my logout.php

    ```php
include("../setpath.php"); // <- this uses session_name() and session_start()
$url = 'http://...';
// Clean-up
$_SESSION['user'] = array();
error_log("Logout: STS");
$auth = new SimpleSAML_Auth_Simple(SSAMLSP);
$auth->logout("$url/loggedout.php");
    ```
- There are cases that produce a weird error. Logs with corrupted file names or meaningless filename:
    - `Trying to get property of non-object ...`
    - `PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1852399989 bytes) in Unknown on line 0`  refresh leads to `NOSTATE`)
   - `PHP Warning:  Unknown: Could not call the sapi_header_callback in Unknown on line 0`

Now, in order not to waste your time I 'd suggest I debug this and come back to you when I have something more specific/solid... the above is all over the place :)

**Comment by jaimeperez** [comment]
Thanks for the feedback @urban-1!

The last errors you are mentioning are indeed related to the PHP bug we were talking about. I'd recommend to start by upgrading PHP itself.

The `ACSPARAMS` error is normal if you reload that page without posting the data again (i.e. selecting the URL and hitting `enter`), as you cannot access that endpoint without proper parameters. The error page should be clear about this: "No SAML response provided". The details may vary a bit between the latest stable and master, though.

The best advice I can give you is to use SAML tracer as much as possible. It will help you see what's actually happening under the hood between the IdP and the SP. Besides, check also the `error.log` of your webserver, as it might contain information about uncaught exceptions that did not make it to the SimpleSAMLphp log.

Let me know what you find out, any help is very much appreciated! 😉

**Comment by urban-1** [comment]
Hi again,

I have installed [this](https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace?hl=en) SAML tracer for Chrome. I tested login and logout over and over again. The only anomaly I can see is that the tracer reports a `GET` with status 0 which points to a "socket closed" or ERR_EMPTY_RESPONSE! Looking at the server's logs at the same time (usually `error_log`, `ssl_error_log` and my app's log), all I can see is _more_ SegFaults... as opposed to the usual single segfault per request (It is scary how naturally this comes out  :smile:!). Therefore, I am pretty sure that all the problems/errors arise from the fact that PHP segafaults in a random way and leaves SSP in a broken state. I don't think that any of the above is related to SSP.

I am reading that this SegFault has been fixed in PHP 5.4.20 and 5.5.2, so I 'll ask tomorrow the sysadmins to update the host... Till this is done I am afraid I cannot provide much more info. However, once the update is rolled out, I can post here to let you know.

Once again, thanks a lot for you time and effort

PS:I will close/answer the SO question and point it there

**Comment by dalexand1** [comment]
I am running into a similar issue with SimpleSAMLphp 1.14.14.  This issue seems to only occur in IE, and it is difficult to reproduce.

**Comment by rafaelferreir4** [comment]
@dalexand1, did you find an answer for this?

**Comment by dalexand1** [comment]
@rafaelferreir4 I was able to track down my issue to a web proxy.  The proxy was stripping out the SAMLResponse argument, so SimpleSAMLphp was actually working as expected.  White-listing the SimpleSAMLphp site in the proxy fixed the issue.  If you are running into a similar issue, I recommend using Fiddler and looking closely at each request
