### ISSUE TITLE
 Class 'SimpleSAML_Logger' not found 

### ISSUE THREAD

**Issue by mitchit1** [simplesamlphp/simplesamlphp#373]
New install
Apache/2.4.6 (CentOS) PHP/5.4.16 
simplesamlphp-1.14.3

Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
Fatal error: Class 'SimpleSAML_Logger' not found in /mnt/simplesaml/config/config.php on line 124

**Comment by jaimeperez** [comment]
Hi @mitchit1!

How did you install SimpleSAMLphp? The `Logger` class has been moved to use namespaces (as will the rest of the code eventually), but that's only in master, which you shouldn't be using...

If you really need to use master, you need to run composer to generate the right autoloader.

**Comment by mitchit1** [comment]
cd /(my directory)
tar xzf simplesamlphp-1.x.y.tar.gz
mv simplesamlphp-1.x.y simplesamlphp

**Comment by jaimeperez** [comment]
Hi again!

Does that happen with all versions? Where did you download them?

I just verified the latest 1.14.3 release. `SimpleSAML_Logger` class is, as it should, defined in `lib/SimpleSAML/Logger.php`. The *composer* autoloader correctly points to it in `vendor/composer/autoload_classmap.php`:

```php
    'SimpleSAML_Logger' => $baseDir . '/lib/SimpleSAML/Logger.php',
```

Take into account that the `SimpleSAML_Logger` class is used all over the place. If this was a bug, it would be affecting everyone, and the software would be completely unusable, but this is the first report that we've had about this.

I'm therefore assuming this could be that you downloaded the wrong tar.gz (for instance, those that github generates automatically) or that you are testing in a way you are not supposed to. Quite difficult to know with so little information.

**Comment by mitchit1** [comment]
It was downloaded 
https://simplesamlphp.org/res/downloads/simplesamlphp-1.14.3.tar.gz 
This is a fresh install, 
New install
Apache/2.4.6 (CentOS) PHP/5.4.16
simplesamlphp-1.14.3

Could you point me in a direction, I would really appreciate it.

**Comment by marek-binkowski-sim** [comment]
I can confirm I have very similar problem after upgrading from simplesamlphp/simplesamlphp v1.14.8 (with simplesamlphp/saml2 v1.10), up to simplesamlphp/simplesamlphp v1.14.9 (which required a downgrade to simplesamlphp/saml2 v1.9 - just in case it is some side issue)

I am using simplesamlphp as a vendor package for symfony 3.1.6 application.

In my controller, this is the simplest action that would start the login request:

```
public function requestAuthAction()
{
    require_once(__DIR__ . '/../../../../../../simplesamlphp/simplesamlphp/lib/_autoload.php');
    $as = new SimpleSAML_Auth_Simple('sp1');
    $as->login([
        'saml:idp' => '---some idp, it does not matter which one---'
    ]);
}
```

Symphony reports an exception:

> The autoloader expected class "SimpleSAML\Logger" to be defined in file "[..app-specific-path..]/../simplesamlphp/simplesamlphp/lib/SimpleSAML/Logger.php". The file was found but the class was not in it, the class name or namespace probably has a typo.
> 
> Stack Trace
> in vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php at line 197   -
>         } catch (SimpleSAML_Error_Exception $e) {
>             SimpleSAML_Auth_State::throwException($state, $e);
>         } catch (Exception $e) {
>             $e = new SimpleSAML_Error_UnserializableException($e);
>             SimpleSAML_Auth_State::throwException($state, $e);
>         }
>         self::loginCompleted($state);

**Comment by jaimeperez** [comment]
Hi @marek-binkowski-sim.

Your exact issue has been discussed, identified and fixed in #517. Your SSP is misconfigured. As soon as you fix your session configuration, you will get rid of the error (and everything else will also work, as a side effect).

**Comment by marek-binkowski-sim** [comment]
I can happily confirm - adding 'session.phpsession.cookiename' to config.php solved the problem with Logger class loading. So simple:

```
<?php
#config.php
$config = [
    ...
    'session.phpsession.cookiename' => 'someRandomSessionName',
    ...
];
```
Thank you Jaime! I still have a State information lost issue in my application, not related with the discussed issue though.

**Comment by rameshnaik5521** [comment]
Hi All,

I also got the same issue but resolved by updating `config.php` file

Since in our case, we have updated the `simplesamlphp master branch` but unfortunately using config.php as older version file only which is causing this issue

I updated `config.php` with help of `config-templates/config.php` and resolved the issue

**Note:**
Personally I noticied `SimpleSAML_Logger` is no loger exists since its moved into namespace in new version simplesamlphp with `SimpleSAML\Logger`

Thanks
