### ISSUE TITLE
Cannot integrate 1.15.0 with projects using Twig 2

### ISSUE THREAD

**Issue by RinkAttendant6** [simplesamlphp/simplesamlphp#753]
With SimpleSAMLphp 1.15.0, I cannot get the ["Integrating authentication with your own application"](https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6) steps working with my application that uses Twig 2.

I am using the Composer autoloader in my application and I've narrowed it down to the `require` line which tries to autoload Twig in my application's vendor dependencies (`vendor`) instead of from where SimpleSAMLphp is installed (`/var/simplesamlphp`).

```php
require '/var/simplesamlphp/lib/_autoload.php';
$as = new \SimpleSAML\Auth\Simple('default-sp');
// also tried the old way: new \SimpleSAML_Auth_Simple('default-sp');
```

This is the error I get:

```
[Thu Dec 21 16:34:09.020522 2017] [php7:error] [pid 16036] [client <snip>] PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Twig_Test in /var/www/app1/vendor/twig/twig/lib/Twig/Extension/Core.php:203
Stack trace:
#0 /var/www/app1/vendor/twig/twig/lib/Twig/ExtensionSet.php(449): Twig_Extension_Core->getTests()
#1 /var/www/app1/vendor/twig/twig/lib/Twig/ExtensionSet.php(429): Twig_ExtensionSet->initExtension(Object(Twig_Extension_Core))
#2 /var/www/app1/vendor/twig/twig/lib/Twig/ExtensionSet.php(398): Twig_ExtensionSet->initExtensions()
#3 /var/www/app1/vendor/twig/twig/lib/Twig/Environment.php(936): Twig_ExtensionSet->getUnaryOperators()
#4 /var/simplesamlphp/vendor/twig/twig/lib/Twig/Lexer.php(382): Twig_Environment->getUnaryOperators()
#5 /var/simplesamlphp/vendor/twig/twig/lib/Twig/Lexer.php(68): Twig_Lexer->getOperatorRegex()
#6 /var/www/app1/vendor/twig/twig/lib/Twig/Environment.php(505): Twig_Lexer->__construct(Object(Twig_Environment))
#7 /var/www/app1/vendor/twig/twig/lib/Twig/Environment.php(561): Twig_Environment->tok in /var/www/app1/vendor/twig/twig/lib/Twig/Extension/Core.php on line 203
```

On the QA environment, I have tested SimpleSAMLphp 1.15.0 with the [TestShib](https://www.testshib.org/) site and the admin interface works correctly, but our application crashes on all pages that require authentication with Shibboleth.

We have rolled back our production environment to SimpleSAMLphp 1.14 in the meantime as it works fine with our application. We really want to upgrade as the new version no longer relies on the mcrypt extension.

Any ideas?

**Comment by thijskh** [comment]
@Olimpiamagliulo This might be something for you to look at...

**Comment by macintoshplus** [comment]
👍

**Comment by macintoshplus** [comment]
Any information for this issue?

**Comment by umpirsky** [comment]
Using this in combination with Twig >1.0 is blocked by composer constraints. Current version of Twig is 2.4.8.

**Comment by ofriedrich** [comment]
In times of increasing number of packages supporting Twig 2 only it would be really nice if simpleSAMLphp would support it too.

For other people searching for a (temporary) solution: [LightSAML](https://github.com/lightSAML) - but does not support logout by default.

**Comment by tvdijen** [comment]
The main issue here is that Twig 2 requires PHP7 and SimpleSAML supports >=5.4.
Perhaps we can support both Twig 1 and 2, but that will require changes to the codebase, because it is currently incompatible with Twig 2.

**Comment by tvdijen** [comment]
Right now, `master` should support Twig2-applications and a PR to backport this functionality to the 1.16 branch is awaiting review. Feedback would be very much appreciated!

**Comment by RinkAttendant6** [comment]
It looks like 1.17 is on track according to https://simplesamlphp.org/releaseplan (the three "not started" items look like they have completed pull requests). If 1.17 is to be released soon then I don't mind trying to upgrade directly from 1.14.
But if it might take a while for 1.17 to be released then perhaps backporting is a good idea. Either way I can only try to upgrade once it's been released in some version.

**Comment by tvdijen** [comment]
Thanks for getting back to me @RinkAttendant6 !
The release plan is under discussion right now, so I have no definitive answer right now.. My hope is that we can release 1.17 later this month..

**Comment by thijskh** [comment]
Fixed in master (1.17)

**Comment by RinkAttendant6** [comment]
It's still not working with 1.17.1. Looks like it is still trying to call the Twig instance in my application's dependencies instead of the library's dependencies. A different error though:

```
PHP Fatal error:  Uncaught Error: Call to a member function setParser() on array in /var/simplesamlphp/vendor/twig/twig/lib/Twig/Parser.php:82
Stack trace:
#0 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(559): Twig_Parser->parse(Object(Twig_TokenStream))
#1 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(591): Twig\\Environment->parse(Object(Twig_TokenStream))
#2 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(408): Twig\\Environment->compileSource(Object(Twig_Source))
#3 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(382): Twig\\Environment->loadClass('__TwigTemplate_...', 'faculty/_base.h...', NULL)
#4 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(360): Twig\\Environment->loadTemplate('faculty/_base.h...')
#5 /var/www/app1/dev/vendor/twig/twig/src/Environment.php(319): Twig\\Environment->load('faculty/_base.h...')
#6 /var/www/app1/dev/src/Web/Faculty/Login.php(51): Twig\\Environment->render('faculty/_base.h...', Array)
#7 [internal function]: Ventus\\Web\\Faculty\\Login->fallback in /var/simplesamlphp/vendor/twig/twig/lib/Twig/Parser.php on line 82
```

My Twig version is 2.7.2.

**Comment by tvdijen** [comment]
I don't see any SimpleSAMLphp in this backtrace...  It starts at your app and ends at Twig, so sorry but I see no reason to reopen this issue in that matter

**Comment by RinkAttendant6** [comment]
The stack trace starts from the SimpleSAMLphp: `/var/simplesamlphp/vendor/twig/twig/lib/Twig/Parser.php:82`

**Comment by tvdijen** [comment]
Yes, SimpleSAML ships with Twig 1.38 by default.. Twig2 is supported though, so `composer update` will likely solve all of your problems
