### ISSUE TITLE
Session_cache_limiter(): Cannot change cache limiter when session is active (PHP 7.2)

### ISSUE THREAD

**Issue by tonis-ls** [simplesamlphp/simplesamlphp#793]
We are updating SSP 1.15.2 from PHP 5.5 to 7.2 and in the log files we find errors like:

Apache log:

[Thu Feb 22 15:41:09.835044 2018] [php7:warn] [pid 11754] [client 172.17.15.231:52937] PHP Warning:  session_cache_limiter(): Cannot change cache limiter when session is active in /var/www/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 122

And simplesamlphp log:

Feb 22 15:41:09 idp ERROR [9a1f0134d6] SimpleSAML_Error_Exception: Error 2 - session_cache_limiter(): Cannot change cache limiter when session is active

[https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.15/lib/SimpleSAML/SessionHandlerPHP.php#L122](url)

**Comment by tvdijen** [comment]
Thanks for reporting this @tonis-ls !
It seems that `session_cache_limiter()` must be called before `session_start()`...
Could you swap line 121 and 122 and see if that fixes the issue for you?

**Comment by tonis-ls** [comment]
Thank you @tvdijen for the quick response. 
The errors are gone after switching lines 121 and 122 in SessionHandlerPHP.php.

**Comment by tvdijen** [comment]
That's great, thanks for testing!
I've fixed this on both the `master` and the `simplesaml-1.15` branch.

**Comment by iamtankist** [comment]
Could be that I'm doing something wrong, but on latest 1.15.4 I'm still getting right after installation at `simplesaml/module.php/core/frontpage_welcome.php`

``` 
Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /srv/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php on line 355

Warning: session_id(): Cannot change session id when headers already sent in /srv/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php on line 363

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /srv/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php on line 119

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /srv/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php on line 121

Warning: Cannot modify header information - headers already sent by (output started at /srv/simplesaml/lib/SimpleSAML/SessionHandlerPHP.php:355) in /srv/simplesaml/templates/includes/header.php on line 40
```

**Comment by tvdijen** [comment]
He he, you're right, that code has become pretty useless since I moved that line before `@session_start();`..
I need to have a closer look at this and find out what the intended behaviour was before I messed with it.. I may have broken something

**Comment by ericuwa** [comment]
Ok, thank you for taking a look.

**Comment by tvdijen** [comment]
@jaimeperez you've tried to fix something [here](https://github.com/simplesamlphp/simplesamlphp/commit/51d3517e6a7a456d00cd46567c7dd39fab875656) that got rendered useless after I touched it [here](https://github.com/simplesamlphp/simplesamlphp/commit/e3557c827cc34c51d7230c28527029469bd51918)..
Now, I'm not sure what you were trying to fix (other than trying to not send cookies)... Can you remember what the issue was with the cookies, and/or can you think of another way to reach this?

**Comment by tvdijen** [comment]
@ericuwa could you test this with the latest `master`?

**Comment by ericuwa** [comment]
I confirm that the changes fixed the issue.

As a side note, I did encounter a similar error in the flush method of Logger, when it was trying to report an error.

```
PHP Stack trace:
PHP   1. SimpleSAML\Logger::flush() simplesamlphp/lib/SimpleSAML/Logger.php:0
PHP   2. SimpleSAML\Session::getSessionFromRequest() simplesamlphp/lib/SimpleSAML/Logger.php:268
PHP   3. SimpleSAML\Session::getSession($sessionId = *uninitialized*) simplesamlphp/lib/SimpleSAML/Session.php:268
PHP   4. SimpleSAML\SessionHandlerPHP->getCookieSessionId() simplesamlphp/lib/SimpleSAML/Session.php:340
PHP   5. session_id(*uninitialized*) simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:173
PHP Warning:  session_id(): Cannot change session id when headers already sent in simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 173
```

After fixing my idp configuration and getting rid of the error, I encountered the following issue.

```
PHP Fatal error:  Uncaught Error: Call to undefined method SAML2\XML\saml\Issuer::setValue() in simplesamlphp/modules/saml/lib/Message.php:500
```

Also, in order to be able to test, I had to revert the change made to line 499 of Message.php
Here is the patch to give you better context.

```
--- simplesamlphp/modules/saml/lib/Message.php	2018-12-12 09:12:49.000000000 -0500
+++ simplesamlphp/modules/saml/lib/Message.php.orig	2018-12-12 09:12:39.000000000 -0500
@@ -496,7 +496,9 @@
 
         // Shoaib: setting the appropriate binding based on parameter in sp-metadata defaults to HTTP_POST
         $ar->setProtocolBinding($protbind);
-        $ar->setIssuer($spMetadata->getString('entityid'));
+        $issuer = new \SAML2\XML\saml\Issuer();
+        $issuer->setValue($spMetadata->getString('entityid'));
+        $ar->setIssuer($issuer);
         $ar->setAssertionConsumerServiceIndex($spMetadata->getInteger('AssertionConsumerServiceIndex', null));
         $ar->setAttributeConsumingServiceIndex($spMetadata->getInteger('AttributeConsumingServiceIndex', null));
```

**Comment by tvdijen** [comment]
Ah, I think you haven't run `composer install` after pulling in the changes from master.. setValue() does exist on the latest version of the saml2-library

**Comment by tvdijen** [comment]
@ericuwa Can you confirm that the issue no longer exists on master and/or 1.17?

**Comment by ericuwa** [comment]
Confirmed.

Everything works great now, thank you.
